# if you want to import your config from another file
# this file will be ignored then and the config will be loaded from this option
import: example.yml # optional

site: # required
  host: https://www.narukoshin.me/login # required
  method: POST # required

bruteforce: # required
  field: password # required

  # method #1
  from: list
  list:
   - example password
   - example password 2

  # method #2
  from: file
  file: /usr/share/wordlists/rockyou.txt
  
  # method 3
  from: stdin
  
  # This option turns off "trying password" messages
  no_verbose: false # optional
  
  # this option will save the password in the file
  output: /home/naru/my_target/password.txt
  
  threads: 20 # optional | default: 5

headers: # optional
  - name: User-Agent
    value: "Mozilla/5.0 (Macintosh; Intel Mac OS)"
  - name: Content-Type
    value: "application/x-www-form-urlencoded; charset=UTF-8"

fields: # optional
  - name: username
    value: admin

on_fail: # required - will be ignored if on_pass is added
  message: Invalid username
  
on_pass: # optional
  message: Welcome
  
crawl: # optional
  url: <token-url> # optional
  name: field-name
  search: ([a-z0-9]+){32} # a regex to find the token
  
# if you want to tunnel all the requests through the proxy
proxy: # optional
    socks: socks5://127.0.0.1:9050?timeout=5s # for Tor proxy

# email settings
email:
  # Email settings that will send the email
  server:
    host: your.server.name
    port: 587
    timeout: 3 # default 30
    email: your.email@address.com
    password: your.password123

  mail:
    # method 1
    recipients: your.email@address.com
    
    # method 2 for multiple recipients
    recipients:
      - your.email@address.com
      - another.email@address.com
      - random.email@address.com
    subject: Your subject text is here
    name: Who Am I ?
    message: "Password: <password>" # a real password will appear in <password> place.